import {
   IPayment,
  IRefundPayment,
} from "@/types/payment"

export const PaymentsData: IPayment[] = [
{  
    sl: 1,
  paymentID: "045HJ",
  ProjectName: "Web dev",
  paymentType: "Bank Wallet",
  accountName:"SBI Bank" ,
  accountNumber:"005002",
  transactionId:"005002" ,
  payAmount : 110,
  paymentDay: "03-02-2025",
  status: "spam",

},
{  
    sl: 2,
  paymentID: "045HJ",
  ProjectName: "App dev",
  paymentType: "Bank",
  accountName:"SBI Bank" ,
  accountNumber:"005002",
  transactionId:"005002" ,
  payAmount : 110,
  paymentDay: "03-02-2025",
  status: "pending",

},
{  
    sl: 3,
  paymentID: "045HJ",
  ProjectName: "App dev",
  paymentType: "Bank",
  accountName:"SBI Bank" ,
  accountNumber:"005002",
  transactionId:"005002" ,
  payAmount : 110,
  paymentDay: "03-02-2025",
  status: "accepted",

},
{  
    sl: 4,
  paymentID: "045HJ",
  ProjectName: "App dev",
  paymentType: "Bank",
  accountName:"SBI Bank" ,
  accountNumber:"005002",
  transactionId:"005002" ,
  payAmount : 110,
  paymentDay: "03-02-2025",
  status: "pending",
 
},
{  
    sl: 5,
  paymentID: "045HJ",
  ProjectName: "App dev",
  paymentType: "Bank wallet",
  accountName:"SBI Bank" ,
  accountNumber:"005002",
  transactionId:"005002" ,
  payAmount : 180,
  paymentDay: "03-02-2025",
  status: "spam",
 
},

]

export const RefundData: IRefundPayment[] = [
  {
    sl: 1,
    refundId: "REF001",
    projectName: "Web Dev",
    refundMethod: "Bank",
    accountName: "John Doe",
    accountNumber: "045001",
    refundAmount: 500,
    refundDay: "2024-04-19",
    status: "Ineligible",
  },
  {
    sl: 2,
    refundId: "REF002",
    projectName: "App Dev",
    refundMethod: "Bank",
    accountName: "Jane Smith",
    accountNumber: "005002",
    refundAmount: 800,
    refundDay: "2024-04-20",
    status: "Pending",
  },
  {
    sl: 3,
    refundId: "REF003",
    projectName: "Web Dev",
    refundMethod: "Bank Wallet",
    accountName: "Michael Johnson",
    accountNumber: "005002",
    refundAmount: 1000,
    refundDay: "2024-04-21",
    status: "Sending",
  },
  {
    sl: 4,
    refundId: "REF004",
    projectName: "App Dev",
    refundMethod: "Bank",
    accountName: "Emily Brown",
    accountNumber: "005402",
    refundAmount: 700,
    refundDay: "2024-04-22",
    status: "Pending",
  },
  {
    sl: 5,
    refundId: "REF005",
    projectName: "Web Dev",
    refundMethod: "Bank Wallet",
    accountName: "Daniel Wilson",
    accountNumber: "005402",
    refundAmount: 600,
    refundDay: "2024-04-23",
    status: "Ineligible",
  },
  {
    sl: 6,
    refundId: "REF006",
    projectName: "Web Dev",
    refundMethod: "Bank Wallet",
    accountName: "Olivia Taylor",
    accountNumber: "045001",
    refundAmount: 900,
    refundDay: "2024-04-24",
    status: "Sending",
  },
  {
    sl: 7,
    refundId: "REF007",
    projectName: "App Dev",
    refundMethod: "Bank",
    accountName: "Sophia Martinez",
    accountNumber: "005400",
    refundAmount: 1200,
    refundDay: "2024-04-25",
    status: "Pending",
  },
]
